@startuml

actor OW as "Organization Worker"

rectangle worldDatabase

rectangle "WHO Organization System" {
    usecase UC1 as "Get all countries in the world"

    usecase UCa as "Print organised by largest population to smallest"

    OW - UC1
    UC1  ..> UCa : include
    UC1  - worldDatabase
}

@enduml
