@startuml

actor OW as "Organization Worker"

rectangle worldDatabase

rectangle "WHO Organization System" {
    usecase UC2 as "The top N populated cities"
    usecase UC2.1 as "in the world"
    usecase UC2.2 as "in a continent"
    usecase UC2.3 as "in a region"
    usecase UC2.4 as "in a country"
    usecase UC2.5 as "in a district"

    usecase UCa as "Print where N is provided by the user"

    OW - UC2
    UC2  ..> UC2.1 : optional
        UC2.1 ..> UCa : include
    UC2  ..> UC2.2 : optional
        UC2.2 ..> UCa : include
    UC2  ..> UC2.3 : optional
        UC2.3 ..> UCa : include
    UC2  ..> UC2.4 : optional
        UC2.4 ..> UCa : include
    UC2  ..> UC2.5 : optional
        UC2.5 ..> UCa : include
    UC2  - worldDatabase


}

@enduml