name: ReportingApp-SEM-GRP3
on: push

jobs:
  build:
    name: ReportingApp action
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Unit Tests
        run: |
          mvn -Dtest=com.napier.sem.CountryTest test
          mvn -Dtest=com.napier.sem.CityTest test
          mvn -Dtest=com.napier.sem.CapitalTest test
      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests
          docker-compose up --abort-on-container-exit

